appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: M1y+2d5S6iZ4Vj0UWAm/boPpCzm5slakBAkFLf99TLd9hiDUYeE84dmokar3GXIVi8HajFymF10iyAXiVqaDdK/ndgGbogWoJ3G7RdUSZdvU8TwtTaFsVvklYmadNRvrEt263sEHqsNfQUOONmP2fAcd5TWZbPWu10pKhPWE6Q5e8H8hZycvSeUvTmzn1hXCYACZSHrs/+KyqiAbXrt6TPf7Kg1JTTzdxOHw2sDx2Ow68jk6Jq8KUdr88xREIv/T36tEQJz8ClGbG20RlAS8DMZC47wod7H3lmZ34rQvlG3vtmqorW5N8UB/wumYwyHMLi382heqkcUW3BXR6e5kUKX0vojua67ji8hAYax8/b1r9TY44eV5OkKK3FuITU/7F5MLdlUbmkUt61j64hkGUBWJ1XTRgsm7DyISHgruDEZNZCzKLi6Lf416TZXBxkvIrBLBedChoFgUVAXnazorGCR7K5mm37XDFqF42R7fxTlZKtBPAyqmsZ3zFsoMCWLFZItapEJIrbj17HnRSR8NQo9uU3hdWQM47P0w1M4FyR63VdpIBDmVE1CnZpZiEVbhZHPQL5HeColx8vbwdCCsGVIfZaoNVE5jpS0/Soe7zJCSaH3F+Vks6lColmmeCxwCSvCyIIAksLJs/jfxRYgvEn7hosPAv8kq8MIWas3rr0M=}
